name: lista_elegante
description: Uma aplicação Flutter elegante para gerenciar sua lista de compras.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^5.0.0
  cupertino_icons: ^1.0.2
  mobile_scanner: ^6.0.10
  http: ^1.5.0
  intl: ^0.20.2
  flutter_slidable: ^3.1.0
  pdf: ^3.10.7
  path_provider: ^2.1.2
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true